### ISSUE TITLE
chore: makes java convention 

### ISSUE THREAD

**Issue by her0807** [Nexters/Don-t-Forget---Server#2]
## 수달이 생각한 컨벤션 

1. 기본적으로 우테코의 자바컨벤션을 따른다.
    1. https://google.github.io/styleguide/javaguide.html
    2. https://myeonguni.tistory.com/1596
2. 불변 변수에는 final을 붙여 불변을 보장한다.
    1. entity의 생성자의 파라미터에는 final을 붙이지 않는다.
    2. 그 외에는 생성자의 파라미터 또한 final을 붙인다.
3. 클래스의 첫 필드 혹은 첫 메서드에는 개행을 추가한다.
    
    ```java
    public User {
    	
        private final String name;
    	  ...
    }
    ```
    
4. 매개변수 개행
    1. 우테코 가로글자수 컨벤션을 넘어가는 순간부터 한줄에 변수 한줄 씩 작성한다.
5. static이 붙은 변수와 static이 붙지 않은 변수 사이에 개행을 추가한다.
6. 서비스에서는 domain을 반환한다.
7. DTO를 변환할때는 롬복의 빌더를 사용한다.
8. 테스트 메서드명
    1. 카멜케이스로 통일한다.
    2. 인수테스트 fixture는 한글로 적는다.
    3. DisplayName
        1. 동사로 통일(ex. ~를 반환한다. / 예외가 발생한다.)
9. 커밋 메세지의 내용은 한글로 작성한다.
    1. ex) `feat: 면담 예약 기능 개발`
10. 컨트롤러에서 반환값이 없을때는 `ResponseEntity<Void>`를 반환한다.
11. 문서화 방식은 Spring RestDocs를 사용한다.
12. 메서드 순서
    1. 사용순서로 정렬한다.
    2. CRUD 순서로 정렬한다.
13. 에러처리
    1. 에러메세지
        1. 기본적으로 사용 클래스 내에서 상수화한다.
        2. 제어자는 protected 로 선언한다.
    2. 에러처리
        1. 추후 논의 - 지금은 필요한 상황에! 리뷰하면서 정하자 
14. 어노테이션 위치 
    1. 길이가 우선이다.
    2. 그 다음은 중요도 순으로 정렬한다. (Spring 관련 설정이 중요하다.)

### 그 외 대표적인 컨벤션
- [네이버](https://naver.github.io/hackday-conventions-java/)

**Comment by worldii** [comment]
1. 테스트는 목으로하나요? 실제 객체로 하나요??? 
2. 패키지 구조도 고민해보면 좋을거 같아여

**Comment by her0807** [comment]
단위 테스트는 -> 목 
통합 테스트 이상은 -> 실제 객체로 
--->
테스트 디비 -> h2
