### ISSUE TITLE
[Git] Commit Message Convention

### ISSUE THREAD

**Issue by her0807** [Nexters/Don-t-Forget---Server#4]
### 정해야할 것 .

1. branch 이름 생성 규칙
2. commit 메세지 통일
3. merge 규칙 정하기

**Comment by her0807** [comment]
### 제안 사항 #1

제안 사항 : `feature` 을 모두 `feat` 으로 통일하는 것은 어떨까? 

생각하게된 배경

- 일반적으로 기능에 대한 커밋 헤더는 `feature` 가 아니라, `feat` 으로 대부분 한다.
- 당근마켓 레포를 찾아본 결과, `feature` 가 아니라 `feat` 으로 PR 제목으로 사용한다.
    
    [[당근마켓](https://github.com/daangn)](https://github.com/daangn)
    

### 제안 사항 #2

제안 사항 : 이슈 내용을 `as-is` 와 `to-be` 으로 구성하면 좋을 것 같다. 


- as-is : 현재의 상태 분석(수정 전 상태)
- to-be : 미래에 원하는 상태 분석(수정 후 개선되었을때의 상태)

생각하게된 배경

- 현재로써는 `구현 사항` 에 대하여 적기로 하였다.
- as-is 는 어떻게 보면 해당 이슈에 대한 배경을 설명해준다. 
시간이 많이 지난 후, 해당 이슈를 찾아 봐야 하는 경우에 as-is가 도움이 될 것 같다.

**Comment by worldii** [comment]
# 1번 브랜치 이름 생성 규칙
- 기본적으로 main, dev, feat/{이슈번호} 형태는 어떨까요?
- 그리고 PR을 날릴때 closes #이슈번호 도 같이 해주면 좋을 거 같아요
#2번 메세지 통일 
- 제한 사항 1번 좋아요 
- 이거는 비슷할 거 같긴 한데 공통적으로 맞춰야 할 필요가 있을 거 같아요 
#3번  
- main -dev :  Rebase and Merge
- dev - feat :  squash and merge
- 참고 자료 : https://meetup.nhncloud.com/posts/122
-
# 제한사항 1번
좋아용 feat ㄱ ㄱ 
# 제한사항 2번 
이거도 좋아요 해당 관련 사항 이슈 템플릿 작성하겠습니다 👍
